config/routes.rb
Rails.application.routes.draw do
  root 'items#index'
  resources :items do
    collection do
    get :kot
    get :pies
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/item.rb
class Item < ApplicationRecord
    validates :name, presence: true, length: { minimum: 2 }
    

    has_rich_text :body
    has_one_attached :cover_image

    enum item_type: %i[kot pies]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: %i[ show edit update destroy ]

  # GET /items or /items.json
  def index
    @items = Item.all.order(name: :asc)
  end

  # GET /items/1 or /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items or /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to item_url(@item), notice: "Item was successfully created." }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1 or /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to item_url(@item), notice: "Item was successfully updated." }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1 or /items/1.json
  def destroy
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url, notice: "Item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def kot
    @items = Item.where(item_type: 'kot')
  end

  def pies
    @items = Item.where(item_type: 'pies')
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.require(:item).permit(:name, :body, :cover_image, :item_type)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/items/_form.html.erb
<%= form_with(model: item) do |form| %>
  <% if item.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
        <% item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>



<div class="form" style="margin:15px 50px 15px 120px">

<div class="my-5">
 <strong>  <%= form.label "Zdjęcie poglądowe" , style: "display: block", class: 'form-label' %> </strong>
  <%= form.file_field :cover_image, class: 'form-control' %>
</div>

<div class="mb-8">
    <%= form.label "Typ rekordu", style: "display: block", class: 'form-label' %>
    <%= form.select :item_type, Item.item_types.keys, { include_blank: '-- Twój wybór --'}, class:"form-select" %>
  </div>

  <div class="mb-8"> 
    <%= form.label "Nazwa rasy", style: "display: block", class: 'form-label' %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>  

  <div class="mb-8">
    <%= form.label "Opis rasy", style: "display: block", class: 'form-label' %>
    <%= form.rich_text_area :body, class: 'form-control' %>
  </div>
  

<br>
  <div class="mb-8">
    <%= form.submit class:"btn btn-success"%>
    <%= link_to "Strona Główna", items_path, class:"btn btn-outline-dark" %>
  </div>
</div>  
<% end %>

app/views/items/_item.html.erb
<div id="<%= dom_id item %>">
<br><br>
<div class="row">
  <h1 style="margin:0px 15px 50px 0px"> <%= item.name %>  </h1>
<div class="image">

  <% if item.cover_image.attached?%>
      <%= image_tag item.cover_image, height:"380px",width:"480px", style:"border-radius:25px"%>
      <% else %>
      <%= image_tag "1.jpg", height:"185px",width:"185px", style:"border-radius:25px"%>
  <% end %>
</div>

  <div class="text">
      <h5 style="margin:0px 15px 50px 0px"><br> <%= item.body %> </h5>
  </div>
  
</div >

</div> 

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render "form", item: @item %>

<br>

<div>
  <%= link_to "Show this item", @item, class:"btn btn-outline-info" %> |
  <%= link_to "Back to items", items_path, class:"btn btn-outline-dark"%>
</div>

app/views/items/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Wszystko</h1>
<!---
<div id="items">
  <% @items.each do |item| %>
    <%= render item %>
    <p>
      <%= link_to "Show this item", item %>
    </p>
  <% end %>
</div> --->
<!-- przycisk dodaj nowego
<%= link_to "New item", new_item_path, class:"btn btn-info" %> --->
<br><br>
<!--- lista rekordów  
<% @items.each do |item| %>
<div class="container">
<div class="row">
  <div class="card" style="border-radius:25px; border-bottom:1rem solid grey; margin-bottom:10px">
   <%= image_tag "1.jpg", weight:"175px", height:"175px"%>
   <h2> <%= item.name %> </h2>
   <p> <%= item.body%> </p>
   <div class="buttom">
   <%= link_to "Show this item", item, class:"btn btn-info" %> <P>
   </div>
  </div>
</div>
</div>
<% end %>
--->

<% (1..12).each_slice (12) do |item| %>
  <div class="row">
    <% @items.each do |item| %>
      <div class="col-lg-4" style="border-radius:25px;">

        <% if item.cover_image.attached?%>
          <%= image_tag item.cover_image, height:"280px",width:"100%", style:"border-radius:25px"%>
          <% else %>
         <%= image_tag "1.jpg", height:"185px",width:"185px", style:"border-radius:25px"%>
         <% end %>

         <div class="text-left">
            <h1 strong class="card-text"> <%= item.name %> </h1> </strong> 
          </div>
            <!--
            <p class="card-text"><%= item.body %></p> -->
            
            <%= item.item_type %>

            <div class="buttom">
              <%= link_to "Więcej", item, class:"btn btn-dark" %> <P>
            </div>
            
      </div>
      
    <% end %>
  </div>

</div>
<% end %>

app/views/items/kot.html.erb
<p style="color: green"><%= notice %></p>

<h1>Lista Kotów</h1>

<% (1..9).each_slice (9) do |item| %>
  <div class="row">
    <% @items.each do |item| %>
      <div class="col-lg-4" style="border-radius:25px;">

        <% if item.cover_image.attached?%>
          <%= image_tag item.cover_image, height:"280px",width:"100%", style:"border-radius:25px"%>
          <% else %>
         <%= image_tag "1.jpg", height:"185px",width:"185px", style:"border-radius:25px"%>
         <% end %>

         <div class="text-left">
            <h1 strong class="card-text"> <%= item.name %> </h1> </strong> 
          </div>
            <!--
            <p class="card-text"><%= item.body %></p> -->
            
            <%= item.item_type %>

            <div class="buttom">
              <%= link_to "Więcej", item, class:"btn btn-dark" %> <P>
            </div>
            
      </div>
      
    <% end %>
  </div>

</div>
<% end %>

app/views/items/new.html.erb
<h1>Nowy Rekord</h1>

<%= render "form", item: @item %>


<div>
  <%= link_to "Strona Główna", items_path, class:"btn btn-outline-dark" %>
</div> 

app/views/items/pies.html.erb
<p style="color: green"><%= notice %></p>

<h1>Lista Psów</h1>


<% (1..9).each_slice (9) do |item| %>
  <div class="row">
    <% @items.each do |item| %>
      <div class="col-lg-4" style="border-radius:25px;">

        <% if item.cover_image.attached?%>
          <%= image_tag item.cover_image, height:"280px",width:"100%", style:"border-radius:25px"%>
          <% else %>
         <%= image_tag "1.jpg", height:"185px",width:"185px", style:"border-radius:25px"%>
         <% end %>

         <div class="text-left">
            <h1 strong class="card-text"> <%= item.name %> </h1> </strong> 
          </div>
            <!--
            <p class="card-text"><%= item.body %></p> -->
            
            <%= item.item_type %>

            <div class="buttom">
              <%= link_to "Więcej", item, class:"btn btn-dark" %> <P>
            </div>
            
      </div>
      
    <% end %>
  </div>

</div>
<% end %>

app/views/items/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @item %>
<br><br><br>

<div>
  <%= link_to "Edit this item", edit_item_path(@item), class:"btn btn-outline-secondary" %> |
  <%= link_to "Back to items", items_path, class:"btn btn-outline-dark"%> | <br><br>

  <%= button_to "Destroy this item", @item, method: :delete, class:"btn btn-outline-danger" %>
  <br>
</div> 

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Koty i Piesy</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %> 
    <%= javascript_importmap_tags %>
    
  </head>

  <body class="container">    
<nav class="navbar mb-5">
  <div class="container-fluid" style="font-size:32px">
   <!-- <a class="navbar-brand" href= <%=items_path %> > Biblioteka</a> -->
    <%= link_to 'Biblioteka', root_path, class:"nav-link"%> 
    <%= link_to 'Koty', kot_items_path, class:"nav-link" %>
    <%= link_to 'Psy', pies_items_path, class:"nav-link"%>
    
    <%= link_to "Dodaj nowy rekord", new_item_path, class:"btn btn-outline-dark" %>

    <form class="d-flex" role="search">
      <input class="form-control me-2" type="search" placeholder="Search" aria-label="Szukaj">
      <button class="btn btn-outline-dark" type="submit">Szukaj</button>
    </form>
  </div>
</nav>


    <%= yield %>

   

  </body>
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0" />
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
</html>